### ISSUE TITLE
Suggestions for a better implementation

### ISSUE THREAD

**Issue by ShivRaiGithub** [Swarnendu0123/adopt-pet#1]
A struct can be used instead of just an index to display more information about the pet like type of animal, age, etc.

**Comment by ShivRaiGithub** [comment]
I would like to work on it so please assign it to me.

**Comment by swrno** [comment]
Assigned to you:)

**Comment by ShivRaiGithub** [comment]
@Swarnendu0123  Can you please add the labels of wob and level to this issue and pr ?
