### ISSUE TITLE
[Documentation Update]: Set up a Readme file for the project

### ISSUE THREAD

**Issue by KiranBaliga** [Swarnendu0123/adopt-pet#14]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

Similar to the code_of_conduct.md file, the project also requires a README.md file to ensure that contributors and users have a clear understanding of the project’s objectives, usage, and how to get involved. Just like the code of conduct establishes guidelines for behavior, the README will serve as a guiding document for understanding and contributing to the project.

### Suggested Change

Creating a readme file from scratch

### Rationale

Objective is the baseline for creating a project for the community

### Urgency

Medium

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 Extd contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by ghost** [comment]
@Swarnendu0123 Please assign this to me as a part of WOB and GSSoC24 Ext Contribution.

**Comment by ghost** [comment]
@Swarnendu0123 Though I know the intent and objective of the project, Can you please provide an overview of the project, including its future goals and purpose. If you already have any resources or notion notes, it would be helpful in generating a good readme file.

**Comment by swrno** [comment]
Overall there are no long term plans for this project. I have just developed it casually.

**Comment by ghost** [comment]
@Swarnendu0123 I have raised the PR. Please review and action accordingly. Thank you!
