### ISSUE TITLE
Add Code of Conduct

### ISSUE THREAD

**Issue by anusha7530** [Swarnendu0123/adopt-pet#3]
We recommend that every repo has a code of conduct. If you don’t feel comfortable creating your own Code of Conduct from scratch we highly recommend using one of the templates provided by GitHub. If you do use a template, please read through the template and ensure that you can and will abide by the Code of Conduct.

Please follow these instructions on how to add a Code of Conduct.

Sample: https://github.com/Girlscript-WOB/Guidelines/blob/main/Project%20Admins/Code%20of%20conduct.md

**Comment by ghost** [comment]
Please assign this task to me as a part of WOB24

**Comment by ghost** [comment]
@Swarnendu0123 Please assign this task to me as a part of WOB24 Contribution. I am a newbie and would like to take part in this campaign as good first issue

**Comment by swrno** [comment]
@KiranBaliga assigned to you:)

**Comment by ghost** [comment]
@Swarnendu0123 I have raised the PR. Please review. Please add WOB24 label. Thank you 🙏🫂
