### ISSUE TITLE
[Documentation Update]: Adde the security

### ISSUE THREAD

**Issue by Dipanita45** [Swarnendu0123/adopt-pet#32]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

Security of the website

### Suggested Change

Security

### Urgency

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 Extd contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Dipanita45** [comment]
Please assign me this issue 
@Swarnendu0123

**Comment by swrno** [comment]
I don't think the issue is assigning matters. The PR assignment matters. You haven't created any PR yet. And for this issue, I don't feel we need this.

**Comment by swrno** [comment]
I suggest you find another issue. If you need any guidance kindly email me clickswarnendu123@gmail.com.
